### ISSUE TITLE
small error on nl_2020.csv table

### ISSUE THREAD

**Issue by Martincccc** [maja601/EuroCrops#20]
653 | Teunisbloem | evening primrose | primrose | 3301083400
hcat2 code is not correct. it should be 3301083500

**Comment by maja601** [comment]
Yes, you're right! Could you add it to you PR, then I'll merge it and release a new Shapefile Version on Zenodo.

**Comment by xchan011** [comment]
The HCAT2 code in both the csv and  Shapefiles have been corrected and released under HCAT3/version 7 of the new Shapefile on Zenodo.
