### ISSUE TITLE
Minor typo HCAT2 extra space to remove

### ISSUE THREAD

**Issue by rdandrimont** [maja601/EuroCrops#22]
Hi @maja601 ,
There is an hidden extra space in main/hcat_core/HCAT2.csv for the class unspecified_root_vegetables . 
The code should be changed:
" 3301299800" -> "3301299800" 
You don't see it but when you load the table, it could cause issues.
Cheers.

**Comment by xchan011** [comment]
Typo has been corrected, thanks for pointing it out :)
