### ISSUE TITLE
Netherlands data goes all the way back to 2009

### ISSUE THREAD

**Issue by glemoine62** [maja601/EuroCrops#25]
Your wiki page on the NL data could use an update:

The correct PDOK link is (you can remove "not recommended"):

https://service.pdok.nl/rvo/brpgewaspercelen/atom/v1_0/basisregistratie_gewaspercelen_brp.xml

it has links to the gpkg set for 2020, 2021 and 2022 and to ZIP file for all off 2009-2019. 

G

**Comment by maja601** [comment]
@glemoine62 fantastic, thank you for letting us know!
