### ISSUE TITLE
HCAT3.csv - line 285 possibly wrong code

### ISSUE THREAD

**Issue by tonish** [maja601/EuroCrops#39]
here is original line 285 of the file :
unspecified_root_vegetables, 330129**98**00

here is my suggestion: 
unspecified_root_vegetables,330129**09**00

**Comment by xchan011** [comment]
Hello, so apart from unspecified_seasons that uses 99 as its code, most unspecified class crops should be under 98. other crops are under 99. A more consistent code convention will be introduced in the upcoming HCAT4.
