### ISSUE TITLE
Crop HCAT2 classification issues

### ISSUE THREAD

**Issue by sbgeophd** [maja601/EuroCrops#7]
I have found some issues with the HCAT2 mappings for some states.

In NL:
**Maïs, snij-** (the most common arable crop) is maize cut for silage. It should have the HCAT2 category green_silo_maize (3301090400)  instead of grain_maize_corn_popcorn (3301010600)
https://github.com/maja601/EuroCrops/blob/main/csvs/country_mappings/nl_2021.csv#L4:

I also notice that almost all grassland classes in multiple datasets are classified simply as "pasture_meadow_grassland_grass" instead of using any higher level categories such as "temporary_grass". I guess this is a deliberate design choice not to get bogged down in how to classify all the different kinds of grassland defined in each dataset? Though this creates situations like in the NL dataset where the class translated as "temporary grassland" doesn't have the HCAT2 category "temporary_grass".

**Comment by maja601** [comment]
Hi @sbgeophd and @Martincccc thank you for pointing out these issues and as discussed with @Martincccc he will raise a PR to address these issues.

Thank you again for supporting me in constantly improving the dataset!!

**Comment by maja601** [comment]
Addressed in [Version 3](https://zenodo.org/record/6868143) :tada:
