### ISSUE TITLE
SK winter soft wheat

### ISSUE THREAD

**Issue by Martincccc** [maja601/EuroCrops#9]
Hi @maja601 

for SK, winter soft wheat seems to be classified as `winter durum wheat`. See below Areas counting in SK from your database using ec_hcat_n field with descend order [unit is 1000ha].

![image](https://user-images.githubusercontent.com/31648099/176442309-be736660-7ce4-435a-a955-9dd4240a6d45.png)

For comparison, find below the equivalent information from our JRC MARS database (+- eurostats) [unit is 1000ha].

![image](https://user-images.githubusercontent.com/31648099/176442529-fc62c43e-2079-41ce-b547-c55c635070b5.png)

Thanks

Martin & @rdandrimont

**Comment by maja601** [comment]
Hi @Martincccc and @rdandrimont thank you for pointing that out! I assume your next PR will solve that issue anyways :)

**Comment by maja601** [comment]
Addressed in [Version 3](https://zenodo.org/record/6868143) :tada:
